### ISSUE TITLE
Cannot clear table after test is executed due to autoCommit is true

### ISSUE THREAD

**Issue by hheg** [database-rider/database-rider#331]
Getting the following error when running a test method with `cleanAfter = true`. Looking through DBUnitExtension it seems like it requires the connections to be in autoCommit = false mode since the code doesn't take care of it. This must be wrong. The code should handle the situation and manage the commits and reset the autoCommit value to whatever it was prior it was running.  
```
java.lang.RuntimeException: Could not clear table test.table
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.clearDatabase(DataSetExecutorImpl.java:677)
	at com.github.database.rider.core.RiderRunner.teardown(RiderRunner.java:97)
	at com.github.database.rider.junit5.DBUnitExtension.afterTestExecution(DBUnitExtension.java:119)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterTestExecutionCallbacks$8(TestMethodTestDescriptor.java:229)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$12(TestMethodTestDescriptor.java:269)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:269)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:268)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterTestExecutionCallbacks(TestMethodTestDescriptor.java:228)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:133)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
....
Caused by: java.sql.SQLException: Can't call commit when autocommit=true
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:67)
	at com.mysql.cj.jdbc.ConnectionImpl.commit(ConnectionImpl.java:794)
	at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:387)
	at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.clearDatabase(DataSetExecutorImpl.java:674)
	... 55 more
```
The test method is annotated like this `@DataSet(value = "data.yml", cleanAfter = true)`
Running with a connection pool set to autoCommit = false makes the test fail because for some reason the data isn't visible to the spring boot app. Running the test without `cleanXXXX` works, but then it's not cleaned up for the next test and that will fail.

The project is using:
Spring boot 2.4.2
HikariCP 4.0.3
Mysql-connection-java 8.0.22
java 11.0.11
dbRider 1.22.0

**Comment by rmpestano** [comment]
> Running the test without cleanXXXX works, but then it's not cleaned up for the next test and that will fail.

Note that tables present in dataset will be cleaned by dbunit but anyway I'll try to add HikariCP config to our SpringBoot sample project to reproduce the issue

Thanks

**Comment by rmpestano** [comment]
Hi again @hheg,

Can you try again with v`1.26.1-SNAPSHOT` ([check here ](https://github.com/database-rider/database-rider#snapshots) how to enable rider snapshots)?  We did some changes in #262  related to autoCommit which might fix your issue. If not, can you provide a reproducer (like the one in issue #262)? 

Thank you

**Comment by hheg** [comment]
Hi @rmpestano.
I tried the version out and it didn't solve my problem. I've been writing a test for this which can be found  [here](https://github.com/hheg/database-rider-problems). I also found that setting up `@DbUnit` annotations for `@BeforeXXX` and `@AfterXXX` don't work due to another bug when I tried to setup tests for showing that connections are leaking. This is also shown in the showcase I linked. I was supposed to validate that there was no leaking going on with this test but stopped since there were other problems.

I will revisit these things after those things are fixed.

**Comment by rmpestano** [comment]
Hi @hheg, thank you for the sample!

The first problem should be fixed now but I couldn't understand the second one (`NotFindingMethodsTest`). Maybe you can create another issue for it? 

Don't forget to use `U` flag to update the rider snapshot on your build.

Thank you again!

**Comment by rmpestano** [comment]
Alright, I think I got the second issue and using `getDeclaredMethods()` solves it, can you test it as well?

**Comment by hheg** [comment]
> Alright, I think I got the second issue and using `getDeclaredMethods()` solves it, can you test it as well?

I think it should follow JUnit5 rules here, and it allows all modifiers but private, and I believe that `getDeclaredMethods` also pickup methods with private modifier so I think it needs additional filtering here.

Even fixing that, the `LeakingConnectionsTest` crashes with a:
```
java.lang.RuntimeException: Could not create dataset to compare.
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.compareCurrentDataSetWith(DataSetExecutorImpl.java:823)
	at com.github.database.rider.junit5.DBUnitExtension.executeExpectedDataSetForCallback(DBUnitExtension.java:212)
	at com.github.database.rider.junit5.DBUnitExtension.afterEach(DBUnitExtension.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachCallbacks$11(TestMethodTestDescriptor.java:253)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$12(TestMethodTestDescriptor.java:269)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:269)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:268)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachCallbacks(TestMethodTestDescriptor.java:252)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.RuntimeException: Could not get driver information from provided connection.
	at com.github.database.rider.core.util.DriverUtils.getDriverName(DriverUtils.java:50)
	at com.github.database.rider.core.connection.RiderDataSource.checkDbType(RiderDataSource.java:175)
	at com.github.database.rider.core.connection.RiderDataSource.init(RiderDataSource.java:96)
	at com.github.database.rider.core.connection.RiderDataSource.<init>(RiderDataSource.java:53)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.getRiderDataSource(DataSetExecutorImpl.java:918)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.compareCurrentDataSetWith(DataSetExecutorImpl.java:812)
	... 55 more
Caused by: java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:515)
	at com.sun.proxy.$Proxy78.getMetaData(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyConnection.getMetaData(ProxyConnection.java:380)
	at com.zaxxer.hikari.pool.HikariProxyConnection.getMetaData(HikariProxyConnection.java)
	at com.example.springboot.LeakingConnectionsTest$WrappingConnection.getMetaData(LeakingConnectionsTest.java:286)
	at com.github.database.rider.core.util.DriverUtils.getDriverName(DriverUtils.java:48)
	... 60 more
```

**Comment by rmpestano** [comment]
> Alright, I think I got the second issue and using getDeclaredMethods() solves it, can you test it as well?

> I think it should follow JUnit5 rules here, and it allows all modifiers but private, and I believe that getDeclaredMethods also pickup methods with private modifier so I think it needs additional filtering here.

If you can declare junit5 hooks in non-public methods (as in your example `NotFindingMethodsTest`) then we need to use `getDeclaredMethods`.

I'll have a look at the leak hunter issue

**Comment by rmpestano** [comment]
Hi again, it should be fixed now unfortunately the rider snapshot could not be deployed on maven central (I'm checking with them) so to test it you'll have to checkout rider locally and run `mvn install -DskipTests`

**Comment by rmpestano** [comment]
Now 1.26.1-SNAPSHOT is deployed on maven central, let me know if this issue is fixed.

Thanks

**Comment by hheg** [comment]
Hi,
Hmm... The test still fails. The `@BeforeEach`  is annotated with a start.yml which should insert a row with id=1 into the db. The actual test will then run inserting a value. The `@AfterEach`  should then validate that there's two elements in the db, `1` and `2`. The `test1` method should be failing since after it has been run there should be `1` and `3` in the db which the assertion on `@AfterEach`  should catch? If everything is working `test2` and `test3` should be passing.

**Comment by rmpestano** [comment]
> If everything is working test2 and test3 should be passing.

That's what I get when I comment out the `assertEquals(1, wrappingDataSource.liveConnections.get());`, which's not related to dbrider

<img width="1080" alt="Screenshot 2021-08-01 at 12 01 11" src="https://user-images.githubusercontent.com/1592273/127766987-0f51e5bc-e7e8-431f-ad3a-3fab6d3074ca.png">

I also enable dbrider leak under (`@DBUnit(caseInsensitiveStrategy = Orthography.LOWERCASE, cacheConnection = false, leakHunter = true)` and the tests are passing meaning that the number of open connections before the tests are the same after the tests

**Comment by hheg** [comment]
You were right about the tests, I was looking at the wrong assertion.

I've pushed a new test that verifies that dbrider is leaking connections. The test should run as declared but fails since the connections are not properly closed. I've added stacktraces which should show where the connections are checked out but a close is never called on them. Each stack with getConnection should have a corresponding close, which it doesn't.

The leak hunter seems to not find these connections leaking.

**Comment by rmpestano** [comment]
Can you please open a new issue so we can diacuss that? Thank you!

**Comment by rmpestano** [comment]
By the way, just checked your latest commit and again, removing your assertion makes it pass:

```		assertEquals(0, wrappingDataSource.liveConnections.get());
```

looks like `wrappingDataSource.liveConnections.get()` is leaving connections opened

**Comment by rmpestano** [comment]
The fix was release in v`1.27.0`, thank you @hheg for all the input on this issue!
